apiVersion: v1
kind: Service
metadata:
  name: cv-onepage-nodeport
spec:
  type: NodePort
  selector:
    app: cv-onepage
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30085  # accessible sur DEVOPS-LAB:30085
