server:
  http_listen_port: 12345

prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs:
    - name: agent
      scrape_configs:
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['localhost:8080']
      remote_write:
        - url: "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push" # replace by grafana-cloud URL
          basic_auth:
            username: "api_key"
            password: "<GRAFANA_CLOUD_API_KEY>"
